### ISSUE TITLE
`FormatDateTime()` not ensuring UTC

### ISSUE THREAD

**Issue by rynop** [jordic/goics#10]
`FormatDateTime()` produces a UTC string (designated by `Z` at the end), however the code does not  enforce that the Time object is in UTC before calling the `Format()` method.

Per the [go Time.Format docs](https://golang.org/pkg/time/#Time.Format), "The time zone attached to the time value affects its output".

As it sits now, if your time object is in America/Chicago and `FormatDateTime()` is called, it will just produce a string with the America/Chicago time and plop a `Z` on the end.

PR incoming with the fix....

**Comment by jordic** [comment]
sounds good!
